apiVersion: git.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-git-config
spec:
  debug: true
  credentials:
    source: Secret
    secretRef:
      namespace: krateo-system
      name: git-token-secret
      key: token