apiVersion: git.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-git-config
spec:
  fromRepoCredentials:
    source: Secret
    secretRef:
      namespace: default
      name: github-token
      key: token
  toRepoCredentials:
    source: Secret
    secretRef:
      namespace: default
      name: github-token
      key: token

