apiVersion: git.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-git-config-gh
spec:
  deploymentServiceUrl: http://deployment.krateoplatformops.io/
  fromRepoCredentials:
    authMethod: basic
    source: Secret
    secretRef:
      namespace: default
      name: github.com-secret
      key: token
  toRepoCredentials:
    authMethod: basic
    source: Secret
    secretRef:
      namespace: default
      name: github.com-secret
      key: token
