apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: provider-git-example-bitbucket
  labels:
    deploymentId: 626c03950944e84673f8b82b
spec:
  forProvider:
    fromRepo:
      url: http://10.99.99.37:7990/scm/jxp/from-repo.git
      path: skeleton
    toRepo:
      url: http://10.99.99.37:7990/scm/jxp/to-repo.git
    configMapKeyRef:
      name: sample-values
      namespace: default
      key: json
  providerConfigRef:
    name: provider-git-config
