apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controller-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-git
spec:
  package: 'ghcr.io/krateoplatformops/crossplane-provider-git:VERSION'
  packagePullPolicy: Always
  packagePullSecrets:
  - name: cr-token
  controllerConfigRef:
    name: controller-config